syntax = "proto3";

package zmk.core;

enum LockState {
    ZMK_STUDIO_CORE_LOCK_STATE_LOCKED = 0;
    ZMK_STUDIO_CORE_LOCK_STATE_UNLOCKED = 1;
}

message Request {
    oneof request_type {
        bool get_device_info = 1;
        bool get_lock_state = 2;
        bool lock = 3;
        bool reset_settings = 4;
        bool get_ble_profiles = 5;
        bool get_tapping_term = 6;
        SetTappingTermRequest set_tapping_term = 7;
        SetBleProfileNameRequest set_ble_profile_name = 8;
        bool get_runtime_state = 9;
    }
}

message Response {
    oneof response_type {
        GetDeviceInfoResponse get_device_info = 1;
        LockState get_lock_state = 2;
        bool reset_settings = 4;
        GetBleProfilesResponse get_ble_profiles = 5;
        GetTappingTermResponse get_tapping_term = 6;
        bool set_tapping_term = 7;
        bool set_ble_profile_name = 8;
        RuntimeState get_runtime_state = 9;
    }
}

message SetTappingTermRequest {
    uint32 tapping_term_ms = 1;
}

message SetBleProfileNameRequest {
    uint32 profile_index = 1;
    string name = 2;
}

message GetTappingTermResponse {
    uint32 tapping_term_ms = 1;
    uint32 default_tapping_term_ms = 2;
}

message GetDeviceInfoResponse {
    string name = 1;
    bytes serial_number = 2;
    string firmware_version = 3;
}

message BleProfileInfo {
    string name = 1;
    bool connected = 2;
}

message GetBleProfilesResponse {
    repeated BleProfileInfo profiles = 1;
    uint32 active_index = 2;
}

message RuntimeState {
    uint32 highest_layer = 1;
    uint32 active_layers_bitmask = 2;
    uint32 battery_central = 3;
    uint32 battery_peripheral = 4;
    bool charging = 5;
}

message Notification {
    oneof notification_type {
        LockState lock_state_changed = 1;
        RuntimeState runtime_state_changed = 2;
    }
}